### ISSUE TITLE
All word xor is incorrect

### ISSUE THREAD

**Issue by TheIronBorn** [vks/xoshiro#2]
The full state xor operation cannot be a single SIMD xor operation, because half of the xors depend on a previous xor.  
Simplifying the lines `s[2] ^= s[0]; s[1] ^= s[2];` for `s[1]` becomes `s[1] ^= s[2] ^ s[0]`

Your full xor operation doesn't do this:
https://github.com/vks/xoshiro/blob/8783637a39bb6e232420d01c10c4441c481adda9/src/lib.rs#L37

**Comment by vks** [comment]
Very good point, that was on oversight on my part. I think this can be fixed with two additional SIMD instructions.

**Comment by vks** [comment]
I fixed the code to actually follow the reference implementation, unfortunately the SIMD version is now apparently slower than the non-SIMD one.
